services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PODTGRES_DB=ny_taxi1
    volumes:
      - "C:<Full path>ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5480:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "8060:80"